### ISSUE TITLE
create an english version

### ISSUE THREAD

**Issue by FerandDalatieh** [dee-dw/bewerbung-latex#1]
Thank you very much for sharing this awesome template of a german job application!

I would be interested in translating it and creating an english version. So it would have the same structure but could be used in germany when the employer asks for an english application.

Please let me know if you would be interested too.

**Comment by dee-dw** [comment]
Hi,

this is a good idea. Maybe I can integrate your translation and via a switch (\SetLanguage{German/English}) the user can change the text language.

Best regards
Dee
