### ISSUE TITLE
Subject between name (Adressat) and letter (Anschreiben) in application.tex

### ISSUE THREAD

**Issue by skriesch** [dee-dw/bewerbung-latex#4]
The subject is between the "Dear name" and the letter text. That should be above of the name.

**Comment by dee-dw** [comment]
it depends. In British English the subject line is placed between salutation and body. In Canada it's the same. In American English it's allowed to place the subject above the salutation (as in German). So you can switch to "American" if you want it the other way around.

References:
Business Subject Line British and American: https://www.ego4u.com/en/business-english/communication/business-letter/subject
Canada Government: https://www.btb.termiumplus.gc.ca/tpv2guides/guides/wrtps/index-eng.html?lang=eng&lettr=indx_catlog_b&page=98tVGYR0s2-U.html

Does this answer your request?

**Comment by skriesch** [comment]
Thank you for references.
I have learned that in another way during my study abroad semester in the UK. I have used the American version now. Thank you!
