### ISSUE TITLE
Add option for smaller fontsize

### ISSUE THREAD

**Issue by nikilase** [dee-dw/bewerbung-latex#6]
For starters, this LaTeX template is really easy to use, thanks for that. But I somehow struggled to fit more content on the first page, especially by using a smaller font size. 

If I change the font size in the documentclass command the whole layout gets smaller, as seen in the images below for a reduction from the standard 12pt to 10pt.

For reference I have used the same number of lines as I did in the actual letter, with the Abstand vorm Anschreiben at 3 for a bit more space.

12pt
![image](https://user-images.githubusercontent.com/38077998/105881824-409bfe00-6005-11eb-9478-71d659a0a290.png)

10pt
![image](https://user-images.githubusercontent.com/38077998/105882084-8d7fd480-6005-11eb-8f01-4f5c395c9f18.png)

**Comment by dee-dw** [comment]
Please use

\KOMAoption{fontsize=10pt}

after \SetzeSchrift. I have no idea why scrartcl changes the border margins if the size is given as option.

Best regards
Dee

**Comment by nikilase** [comment]
Thanks, that worked almost flawless. 
Whilst inserting it after \SetzeSchrift it gives an error for scrbase, although it seems to create the PDF just fine. Though that can be remedied by changing the \KOMAoption in your bewerbung-latex.sty and just adding the fontsize there. 

Now I can fit a longer text in the initial letter and still have my signature correctly positioned.

Much appreciated 
Niklas

**Comment by nikilase** [comment]
Sorry, I was blind and didn't see that \KOMAoption was already used, just commented out, after \SetzeSchrift
