### ISSUE TITLE
Add Matrix Links

### ISSUE THREAD

**Issue by JokerGermany** [dee-dw/bewerbung-latex#8]
Hi I would like to add my Matrix Link.

I copied the Text of Linkedin and modified it, but how do i implement the icon
https://github.com/vector-im/logos/blob/master/matrix/matrix%20favicon.svg
```
\newcommand*{\DefMatrix}{}
[...]
\newcommand*{\Matrix}[1]{%
	\renewcommand*{\DefMatrix}{Matrix: \href{https://matrix.org}\\}%
	\addtocounter{ProfilZeilen}{-1}%
}
```

Can you help me with this?

**Comment by dee-dw** [comment]
I'm not quite sure what you want to do. I think you have created a SVG icon and want to display this in your document? That's a more general question. I would convert the SVG to PDF and include die PDF icon.

But I think that has nothing to do with "bewerbung-latex".

Best regards
Dee
